baseURL = "https://reverent-kowalevski-b25581.netlify.com/"
languageCode = "en-UK"
title = "assembli"
description = "a Blog by assembli"
config = "config.toml"
tags = ["blog", "assembli", "SEO"]
theme = "onepress"
# enable Google Analytics
googleAnalytics = " "
# Disable comments by leaving disqusShortname empty
disqusShortname = "your disqus shortname"
copyright = "Copyright © 2019, Wilber Wanjira; all rights reserved."
canonifyURLS = true
paginate = 12

[params]
	author = "Assembli"
  bio = "a global movement whose mission is to bring free african educational content to the world to which anyone can contribute"
	logo = "/images/logo.png"
	avatar = "/images/logo.png" #change to author.png (wwanjira)
	opengraphImage = "/images/logo.jpg"
	enableRSS = true

	customCSS = true
  readMore = "Read Up"

  # Social
	twitter  = "https://twitter.com/assembli-africa"
	github   = ""
	facebook  = "https://facebook.com/assembli-africa"
  linkedin  = ""

  # Email
	email = "mailto:t@assembli.africa"

  # Widget
  widgets = true

  # Author box and Share button
  authorCard = true
  shareButton = true

  # Code highlighting with highlight.js
  highlightJS = true

	#enable subscription
	subscribeLink = true

# Taxonomies
[taxonomies]
    tag = "tags"
